language: python
sudo: false
python:
  - 2.7
  - 3.6
  - pypy
  - pypy3
jobs:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
  allow_failures:
    # pypy3 7.1 is triggering failures
    # https://bitbucket.org/pypy/pypy/issues/3006/codecsdecode-failure-hex-decoder-returned
    - python: pypy3
script:
  - coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com
env:
    global:
        - PYTHONHASHSEED=random
        - PIP_UPGRADE_STRATEGY=eager
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U coveralls coverage
  - pip install -U zope.testrunner
  - pip install -U -e ".[test]"

cache: pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
